### PR TITLE
Fix BinaryType with dbal 4

### LINKED ISSUE #659: Invalid mapping type to property type check for binary mapping since DBAL v.4
Since DBAL v.4 binary mapping [converts](https://github.com/doctrine/dbal/blob/4.2.x/UPGRADE.md#bc-break-changes-to-handling-binary-fields) DB value to PHP string instead of resource. But PHPStan check produces an error in this case:
```
Property Entity\Foo::$bar type mapping          
         mismatch: database can contain resource|null but property expects     
         string|null.
```

### PR DESCRIPTION
**Pull request by VincentLanglet**
Closes https://github.com/phpstan/phpstan-doctrine/pull/669
Closes https://github.com/phpstan/phpstan-doctrine/issues/659

### CODE REVIEW

File: tests/Rules/Doctrine/ORM/EntityColumnRuleTest.php [hunk 1]
```diff
@@ -271,12 +271,26 @@ public function testSuperclass(?string $objectManagerLoader): void
...
-				17,
-			],
-		]);
+
+		$dbalVersion = InstalledVersions::getVersion('doctrine/dbal');
+		$hasDbal4 = $dbalVersion !== null && strpos($dbalVersion, '4.') === 0;
+		if ($hasDbal4) {
+			$errors = [
+				[
+					'Property PHPStan\Rules\Doctrine\ORM\MyBrokenSuperclass::$five type mapping mismatch: database can contain string but property expects int.',
```
Comment (ondrejmirtes) [inline tests/Rules/Doctrine/ORM/EntityColumnRuleTest.php]: Instead of putting the entire `$errors` assignment in an if, do the assignment once and only change the part of the string that changes with `sprintf` and ternary operator.

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]

File: tests/Rules/Doctrine/ORM/EntityColumnRuleTest.php [hunk 2]
```diff
@@ -478,4 +486,33 @@ public function testBug679(?string $objectManagerLoader): void
...
+	{
+		$this->allowNullablePropertyForRequiredField = false;
+		$this->objectManagerLoader = $objectManagerLoader;
+
+		$dbalVersion = InstalledVersions::getVersion('doctrine/dbal');
+		$hasDbal4 = $dbalVersion !== null && strpos($dbalVersion, '4.') === 0;
+		if ($hasDbal4) {
+			$errors = [
+				[
+					'Property PHPStan\Rules\Doctrine\ORM\MyEntity659::$binaryResource type mapping mismatch: database can contain string but property expects resource.',
```
Comment (ondrejmirtes) [inline tests/Rules/Doctrine/ORM/EntityColumnRuleTest.php:519]: Do the same thing with sprintf here

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]

File: tests/Rules/Doctrine/ORM/EntityColumnRuleTest.php (hunk 2 above)
Comment (VincentLanglet) [reply tests/Rules/Doctrine/ORM/EntityColumnRuleTest.php:519]: It's not
- the same property
- the same type
- the same line

But I can still do it

Comment (ondrejmirtes) [reply tests/Rules/Doctrine/ORM/EntityColumnRuleTest.php:519]: Please remove the last commit, I thought it's the same error and only the type is different. This change really doesn't make sense 😊

And please rebase the PR.

**Comment by ondrejmirtes** [comment]
Thank you.
