### PR TITLE
First-class callable crash on Expr methods

### LINKED ISSUE #711: Crash with phpstan 2.1.32
v2.1.31 was ok.

```php
<?php

declare(strict_types=1);

namespace Project\Foo;

use Project\Foo\Operator;
use Doctrine\ORM\EntityManagerInterface;
use Ds\Map;
use InvalidArgumentException;

final readonly class DoctrineRepository
{
    public function __construct(private EntityManagerInterface $entityManager)
    {
    }

    public function foo(Operator $operator): Map
    {
        $queryBuilder = $this->entityManager->createQueryBuilder();
        $expr = $queryBuilder->expr();

        $comparator = match ($operator) {
            Operator::Eq => $expr->in(...),
            Operator::Neq=> $expr->notIn(...),
        };

        ...
```

```
 -- --------------------------------------------------------------------------- 
     Error                                                                      
 -- --------------------------------------------------------------------------- 
     Internal error: Too few arguments to function                              
     Doctrine\ORM\Query\Expr::in(), 0 passed in                                 
     /project/vendor/phpstan/phpstan-doctrine/src/Type/Doctrine  
     /QueryBuilder/Expr/ExpressionBuilderDynamicReturnTypeExtension.php on      
     line 77 and exactly 2 expected while analysing file                        
     /project/src/DoctrineRepository.php                                                               
     Post the following stack trace to                                          
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.yaml:    
     ## /project/vendor/doctrine/orm/src/Query/Expr.php(393)     
     #0                                                                         
     /project/vendor/phpstan/phpstan-doctrine/src/Type/Doctrine  
     /QueryBuilder/Expr/ExpressionBuilderDynamicReturnTypeExtension.php(77):    
     Doctrine\ORM\Query\Expr->in()                                              
     #1                                                                         
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/MutatingScope.php(4044):                                            
     PHPStan\Type\Doctrine\QueryBuilder\Expr\ExpressionBuilderDynamicReturnTyp  
     eExtension->getTypeFromMethodCall()                                        
     #2                                                                         
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/MutatingScope.php(1582):                                            
     PHPStan\Analyser\MutatingScope->methodCallReturnType()                     
     #3                                                                         
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/MutatingScope.php(642):                                             
     PHPStan\Analyser\MutatingScope->resolveType()                              
     #4                                                                         
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/De  
     pendency/DependencyResolver.php(207):                                      
     PHPStan\Analyser\MutatingScope->getType()                                  
     #5                                                                         
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/De  
     pendency/DependencyResolver.php(446):                                      
     PHPStan\Dependency\DependencyResolver->resolveDependencies()               
     #6                                                                         
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/FileAnalyser.php(192):                                              
     PHPStan\Dependency\DependencyResolver->resolveDependencies()               
     #7                                                                         
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/No  
     de/ClassStatementsGatherer.php(116):                                       
     PHPStan\Analyser\FileAnalyser->{closure:PHPStan\Analyser\FileAnalyser::a   
     nalyseFile():114}()                                                        
     #8                                                                         
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(716):                                         
     PHPStan\Node\ClassStatementsGatherer->__invoke()                           
     #9                                                                         
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(820):                                         
     PHPStan\Analyser\NodeScopeResolver::{closure:PHPStan\Analyser\NodeScopeRe  
     solver::processStmtNode():715}()                                           
     #10                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(3627):                                        
     PHPStan\Analyser\NodeScopeResolver::{closure:PHPStan\Analyser\NodeScopeRe  
     solver::processStmtNode():819}()                                           
     #11                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(2049):                                        
     PHPStan\Analyser\NodeScopeResolver->callNodeCallbackWithExpression()       
     #12                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(2047):                                        
     PHPStan\Analyser\NodeScopeResolver->processExprNode()                      
     #13                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(3116):                                        
     PHPStan\Analyser\NodeScopeResolver->processExprNode()                      
     #14                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(2076):                                        
     PHPStan\Analyser\NodeScopeResolver->processExprNode()                      
     #15                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(4326):                                        
     PHPStan\Analyser\NodeScopeResolver->{closure:PHPStan\Analyser\NodeScopeR   
     esolver::processExprNode():2061}()                                         
     #16                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(2061):                                        
     PHPStan\Analyser\NodeScopeResolver->processAssignVar()                     
     #17                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(819):                                         
     PHPStan\Analyser\NodeScopeResolver->processExprNode()                      
     #18                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(522):                                         
     PHPStan\Analyser\NodeScopeResolver->processStmtNode()                      
     #19                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(955):                                         
     PHPStan\Analyser\NodeScopeResolver->processStmtNodes()                     
     #20                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(522):                                         
     PHPStan\Analyser\NodeScopeResolver->processStmtNode()                      
     #21                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(1085):                                        
     PHPStan\Analyser\NodeScopeResolver->processStmtNodes()                     
     #22                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(522):                                         
     PHPStan\Analyser\NodeScopeResolver->processStmtNode()                      
     #23                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(715):                                         
     PHPStan\Analyser\NodeScopeResolver->processStmtNodes()                     
     #24                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(522):                                         
     PHPStan\Analyser\NodeScopeResolver->processStmtNode()                      
     #25                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(899):                                         
     PHPStan\Analyser\NodeScopeResolver->processStmtNodes()                     
     #26                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(522):                                         
     PHPStan\Analyser\NodeScopeResolver->processStmtNode()                      
     #27                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(850):                                         
     PHPStan\Analyser\NodeScopeResolver->processStmtNodes()                     
     #28                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/NodeScopeResolver.php(470):                                         
     PHPStan\Analyser\NodeScopeResolver->processStmtNode()                      
     #29                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/An  
     alyser/FileAnalyser.php(220):                                              
     PHPStan\Analyser\NodeScopeResolver->processNodes()                         
     #30                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/Co  
     mmand/WorkerCommand.php(149):                                              
     PHPStan\Analyser\FileAnalyser->analyseFile()                               
     #31                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/vendor  
     /evenement/evenement/src/EventEmitterTrait.php(111):                       
     PHPStan\Command\WorkerCommand::{closure:PHPStan\Command\WorkerCommand::ru  
     nWorker():126}()                                                           
     #32                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/vendor  
     /clue/ndjson-react/src/Decoder.php(117):                                   
     _PHPStan_e870ac104\Evenement\EventEmitter->emit()                          
     #33                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/vendor  
     /evenement/evenement/src/EventEmitterTrait.php(111):                       
     _PHPStan_e870ac104\Clue\React\NDJson\Decoder->handleData()                 
     #34                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/vendor  
     /react/stream/src/Util.php(62):                                            
     _PHPStan_e870ac104\Evenement\EventEmitter->emit()                          
     #35                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/vendor  
     /evenement/evenement/src/EventEmitterTrait.php(111):                       
     _PHPStan_e870ac104\React\Stream\Util::{closure:_PHPStan_e870ac104\React\S  
     tream\Util::forwardEvents():61}()                                          
     #36                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/vendor  
     /react/stream/src/DuplexResourceStream.php(168):                           
     _PHPStan_e870ac104\Evenement\EventEmitter->emit()                          
     #37                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/vendor  
     /react/event-loop/src/StreamSelectLoop.php(201):                           
     _PHPStan_e870ac104\React\Stream\DuplexResourceStream->handleData()         
     #38                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/vendor  
     /react/event-loop/src/StreamSelectLoop.php(173):                           
     _PHPStan_e870ac104\React\EventLoop\StreamSelectLoop->waitForStreamActivi   
     ty()                                                                       
     #39                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/src/Co  
     mmand/WorkerCommand.php(105):                                              
     _PHPStan_e870ac104\React\EventLoop\StreamSelectLoop->run()                 
     #40                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/vendor  
     /symfony/console/Command/Command.php(259):                                 
     PHPStan\Command\WorkerCommand->execute()                                   
     #41                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/vendor  
     /symfony/console/Application.php(868):                                     
     _PHPStan_e870ac104\Symfony\Component\Console\Command\Command->run()        
     #42                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/vendor  
     /symfony/console/Application.php(261):                                     
     _PHPStan_e870ac104\Symfony\Component\Console\Application->doRunCommand()   
     #43                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/vendor  
     /symfony/console/Application.php(157):                                     
     _PHPStan_e870ac104\Symfony\Component\Console\Application->doRun()          
     #44                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/bin/ph  
     pstan(99):                                                                 
     _PHPStan_e870ac104\Symfony\Component\Console\Application->run()            
     #45                                                                        
     phar:///project/vendor/phpstan/phpstan/phpstan.phar/bin/ph  
     pstan(100):                                                                
     {closure:phar:///project/vendor/phpstan/phpstan/phpstan.ph  
     ar/bin/phpstan:14}()                                                       
     #46 /project/vendor/phpstan/phpstan/phpstan(8):             
     require('...')                                                             
     #47 /project/vendor/bin/phpstan(119): include('...')        
     #48 {main}                                                                 
 -- --------------------------------------------------------------------------- 
```

### PR DESCRIPTION
**Pull request by simPod**
Fixes https://github.com/phpstan/phpstan-doctrine/issues/711

Repro https://github.com/phpstan/phpstan-doctrine/actions/runs/22821964729/job/66196045235?pr=735#step:9:28

When first-class callable syntax ($expr->in(...)) is used inside match arms or assigned to variables, PHPStan resolves the closure and visits the extension with a MethodCall where isFirstClassCallable() is false and getArgs() is empty. This causes the actual Expr method to be called with 0 arguments, crashing with ArgumentCountError.

Fix with try/catch Throwable around the reflective method invocation for indirect cases (match arms, variable assignments). We also need to cover TypeError from ORM 3.x's typed signatures, plus any other unexpected exception from the reflective call.

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -9,6 +9,7 @@ tests:
 lint:
 	php vendor/bin/parallel-lint --colors \
 		--exclude tests/Rules/DeadCode/data/bug-383.php \
+		--exclude tests/Rules/Doctrine/ORM/data/query-builder-first-class-callable.php \
```
Comment (VincentLanglet) [inline Makefile]: Why do you need ot exclude the file from linting for every php version ?

Does the usual `// lint >= 8.1` in the file work for this repository ?

File: tests/Rules/Doctrine/ORM/QueryBuilderDqlFirstClassCallableTest.php [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+			new ObjectMetadataResolver(__DIR__ . '/entity-manager.php', __DIR__ . '/../../../../tmp'),
+			true,
+		);
+	}
+
+	public function testFirstClassCallableInMatchArm(): void
+	{
+		if (PHP_VERSION_ID < 80100) {
+			self::markTestSkipped('Test requires PHP 8.1.');
+		}
```
Comment (VincentLanglet) [inline tests/Rules/Doctrine/ORM/QueryBuilderDqlFirstClassCallableTest.php]:
```
#[RequiresPhp('>= 8.1')]
```
maybe ?

File: src/Type/Doctrine/QueryBuilder/Expr/ExpressionBuilderDynamicReturnTypeExtension.php [hunk 3]
```diff
@@ -74,7 +79,12 @@ public function getTypeFromMethodCall(MethodReflection $methodReflection, Method
 			return null;
 		}
 
-		$exprValue = $expr->{$methodReflection->getName()}(...$args);
+		try {
```
Comment (VincentLanglet) [inline src/Type/Doctrine/QueryBuilder/Expr/ExpressionBuilderDynamicReturnTypeExtension.php:78]: You seems to introduce 2 fix:
- The isFirstClassCallable check
- The ArgumentCountError try/catch

Which one is really fixing the test you're adding ?
And could we have a test for the other fix ?

File: Makefile (hunk 1 above)
Comment (simPod) [reply Makefile]: Did not know about this, works

File: tests/Rules/Doctrine/ORM/QueryBuilderDqlFirstClassCallableTest.php (hunk 2 above)
Comment (simPod) [reply tests/Rules/Doctrine/ORM/QueryBuilderDqlFirstClassCallableTest.php]: This is not available in phpunit v9

File: src/Type/Doctrine/QueryBuilder/Expr/ExpressionBuilderDynamicReturnTypeExtension.php (hunk 3 above)
Comment (simPod) [reply src/Type/Doctrine/QueryBuilder/Expr/ExpressionBuilderDynamicReturnTypeExtension.php:78]: ArgumentCountError try catch is the actual fix.

I added isFirstClassCallable check to prevent useless work by phpstan. But I guess it just adds complexity so I removed it.

Comment (VincentLanglet) [reply src/Type/Doctrine/QueryBuilder/Expr/ExpressionBuilderDynamicReturnTypeExtension.php:78]: Should we catch something else ?
Like TypeError if we pass a wrong var in the analyzed code ?

`->in($array, $string)` for instance (?)

Then maybe any Throwable in case the method is throwing any exception (?)

`->orX(foo: $foo)` may throw a `BadMethodCallException`

Comment (simPod) [reply src/Type/Doctrine/QueryBuilder/Expr/ExpressionBuilderDynamicReturnTypeExtension.php:78]: Ad TypeError — Doctrine Expr methods accept mixed parameters, so no TypeError is thrown even with wrong types (e.g. ->in(null, null) works fine).

And ad BadMethodCallException / named args — processArgs() strips named arg names and passes values positionally, so ->orX(foo: 'bar') becomes ->orX('bar') which is valid. If processArgs can't resolve an arg at all, it throws DynamicQueryBuilderArgumentException which is already caught before reaching the reflective call.

Comment (VincentLanglet) [reply src/Type/Doctrine/QueryBuilder/Expr/ExpressionBuilderDynamicReturnTypeExtension.php:78]: > Ad TypeError — Doctrine Expr methods accept mixed parameters, so no TypeError is thrown even with wrong types (e.g. ->in(null, null) works fine).

I'm unsure about this, it might depend on the doctrine orm version cause here it's typed with something else than mixed.
https://github.com/doctrine/orm/blob/4262eb495b4d2a53b45de1ac58881e0091f2970f/src/Query/Expr.php#L393

Comment (simPod) [reply src/Type/Doctrine/QueryBuilder/Expr/ExpressionBuilderDynamicReturnTypeExtension.php:78]: Oh I see. Let's catch Throwable then

**Review by VincentLanglet — APPROVED** [review]

File: src/Type/Doctrine/QueryBuilder/Expr/BaseExpressionDynamicReturnTypeExtension.php [hunk 4]
```diff
@@ -55,7 +56,12 @@ public function getTypeFromMethodCall(MethodReflection $methodReflection, Method
 			return null;
 		}
 
-		$exprValue = $expr->{$methodReflection->getName()}(...$args);
+		try {
+			$exprValue = $expr->{$methodReflection->getName()}(...$args);
+		} catch (Throwable $e) {
+			return null;
+		}
+
```
Comment (staabm) [inline src/Type/Doctrine/QueryBuilder/Expr/BaseExpressionDynamicReturnTypeExtension.php:64]: this change is not covered by a test it seems

Comment (simPod) [reply src/Type/Doctrine/QueryBuilder/Expr/BaseExpressionDynamicReturnTypeExtension.php:64]: added https://github.com/phpstan/phpstan-doctrine/pull/735/changes#diff-d9ed5616dc0a146a21995d4d6f73226e97c9570c7c8ee3504d925ca7a804e844

**Comment by staabm** [comment]
thank you!

File: src/Type/Doctrine/QueryBuilder/Expr/BaseExpressionDynamicReturnTypeExtension.php [hunk 5]
```diff
@@ -55,7 +56,12 @@ public function getTypeFromMethodCall(MethodReflection $methodReflection, Method
 			return null;
 		}
 
-		$exprValue = $expr->{$methodReflection->getName()}(...$args);
+		try {
+			$exprValue = $expr->{$methodReflection->getName()}(...$args);
+		} catch (Throwable $e) {
```
Comment (staabm) [inline src/Type/Doctrine/QueryBuilder/Expr/BaseExpressionDynamicReturnTypeExtension.php:61]: @simPod can we use a more specific exception type so we don't swallow everything which might pop up?

Comment (simPod) [reply src/Type/Doctrine/QueryBuilder/Expr/BaseExpressionDynamicReturnTypeExtension.php:61]: I changed it based on this https://github.com/phpstan/phpstan-doctrine/pull/735#discussion_r2901979787. We can add just ArgumentCountError and TypeError for now if you want.

Comment (staabm) [reply src/Type/Doctrine/QueryBuilder/Expr/BaseExpressionDynamicReturnTypeExtension.php:61]: yeah, IMO catching all Throwable's and swallow them could get a big source of trouble in the future.

Comment (VincentLanglet) [reply src/Type/Doctrine/QueryBuilder/Expr/BaseExpressionDynamicReturnTypeExtension.php:61]: @staabm Why not swallow every exception ?

To me it's similar to dynamic return exception which does call with `@` or try/catch
https://github.com/phpstan/phpstan-src/blob/ea0260a7f9378d00bd91c766fc2e3afae8002303/src/Type/Php/SimpleXMLElementXpathMethodReturnTypeExtension.php#L44

But here we don't know exactly the method (`$methodReflection->getName()`) nor the params, so we have to handle every possible error to avoid an hard crash.

Comment (staabm) [reply src/Type/Doctrine/QueryBuilder/Expr/BaseExpressionDynamicReturnTypeExtension.php:61]: throwing away anything in all cases might lead to bugs beeing unnoticed when the method beeing called might start trying to tell us something and we don't see it anywhere

Comment (VincentLanglet) [reply src/Type/Doctrine/QueryBuilder/Expr/BaseExpressionDynamicReturnTypeExtension.php:61]: `return null;` just mean we're not inferring the return type i.e. it's just like the extension is not installed for this dedicated expression.

If someone write a wrong expression like `in(new Obj(), new Obj())` instead of crashing PHPStan will
- not inferring the return type
- use the default return type of the expr/querybuilder
- report a classic error "in expects string, got object"

And as soon as it's fixed by the user, the return type will be computed

Comment (staabm) [reply src/Type/Doctrine/QueryBuilder/Expr/BaseExpressionDynamicReturnTypeExtension.php:61]: I see. lets keep it. thanks for the feedback.
